pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
  publish:
    image: plugins/docker
    repo: pmawyer/node-demo
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    dry_run: false # remove this to publish.
  harness-deploy:
    image: luisredda/drone-harness-plugin
    settings:  
    application: "Patrick-Workspace"
    type: "PIPELINE"
    entityname: "pm-drone-test-pipeline"
    accountid:
      from_secret: harness_se_acctid
    apikey: 
      from_secret: harness_se_apikey
    body: |
     variableInputs: [ 
      {
        name: "Service"
        variableValue: {
          type: NAME
          value: "pm-drone-test"
        }
      }
      ], 
      serviceInputs: [ {
        name: "pm-drone-test", 
        artifactValueInput: {
          valueType: BUILD_NUMBER
          buildNumber: {
            buildNumber: "latest"
      artifactSourceName: "pmawyer_node-demo"
          }
        }}  ]
    when:
      repo:
      - pmawyer/drone-with-nodejs
